2024-04-17T00:00:01 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1476.0, "memory_total": 4954.0, "memory_usage": 0.29794105773112634, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312001.090949, "uuid": "4faba9e5e45844bb96d3a978b89c033b"}
2024-04-17T00:00:01 {"block_run_id": 43, "block_uuid": "load_fear_greed_index", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 9, BlockRun 43: pipeline binance_fear_greed_pipeline block load_fear_greed_index", "timestamp": 1713312001.783494, "uuid": "75f3bea4ee3a4144b86f6bb0e3e08a6d"}
2024-04-17T00:00:01 {"block_run_id": 46, "block_uuid": "load_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 9, BlockRun 46: pipeline binance_fear_greed_pipeline block load_binance", "timestamp": 1713312001.783341, "uuid": "7c851008f81c4177b5799fc5383d1114"}
2024-04-17T00:00:02 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1549.0, "memory_total": 4954.0, "memory_usage": 0.31267662494953574, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312002.103145, "uuid": "c9c4f8408e4649afa65fee902e67da2e"}
2024-04-17T00:00:03 {"block_run_id": 43, "block_uuid": "load_fear_greed_index", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 43 (block_uuid: load_fear_greed_index) completes.", "timestamp": 1713312003.836643, "uuid": "05b69d11b1cc41db943e8f5ff0998c32"}
2024-04-17T00:00:07 {"block_run_id": 46, "block_uuid": "load_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 46 (block_uuid: load_binance) completes.", "timestamp": 1713312007.530117, "uuid": "c2a7f61c070b4471abbb24d993fecd6f"}
2024-04-17T00:00:10 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1536.0, "memory_total": 4954.0, "memory_usage": 0.31005248284214776, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312010.436035, "uuid": "03dd3f0c9f814059b3e4a892d43cc5f1"}
2024-04-17T00:00:10 {"block_run_id": 44, "block_uuid": "transform_fear_greed_index", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 9, BlockRun 44: pipeline binance_fear_greed_pipeline block transform_fear_greed_index", "timestamp": 1713312010.998494, "uuid": "fb614d352a3b4d069ed18935e0550ad9"}
2024-04-17T00:00:11 {"block_run_id": 47, "block_uuid": "transform_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 9, BlockRun 47: pipeline binance_fear_greed_pipeline block transform_binance", "timestamp": 1713312011.036604, "uuid": "beea40c2dcd84683bf7455e93f3c5ba8"}
2024-04-17T00:00:20 {"cpu": 0.0322265625, "cpu_total": 8, "cpu_usage": 0.0040283203125, "memory": 2082.0, "memory_total": 4954.0, "memory_usage": 0.42026645135244245, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312020.905685, "uuid": "f62b66188bec4f509c29c42353a98879"}
2024-04-17T00:00:30 {"cpu": 0.05908203125, "cpu_total": 8, "cpu_usage": 0.00738525390625, "memory": 2802.0, "memory_total": 4954.0, "memory_usage": 0.5656035526846992, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312030.485714, "uuid": "e5e703f2c7d64dc69f6adae766adb0e5"}
2024-04-17T00:00:39 {"block_run_id": 47, "block_uuid": "transform_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 47 (block_uuid: transform_binance) completes.", "timestamp": 1713312039.340019, "uuid": "71619f1cfe3e4057bc38fe817c8c6ba3"}
2024-04-17T00:00:41 {"cpu": 0.3359375, "cpu_total": 8, "cpu_usage": 0.0419921875, "memory": 3002.0, "memory_total": 4954.0, "memory_usage": 0.6059749697214373, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312041.235386, "uuid": "8dbc40a43b854ea8a2dcbcd6d071bd1f"}
2024-04-17T00:00:42 {"block_run_id": 48, "block_uuid": "export_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 9, BlockRun 48: pipeline binance_fear_greed_pipeline block export_binance", "timestamp": 1713312042.738185, "uuid": "7c9c258f404a455587c93604bb834f73"}
2024-04-17T00:00:44 {"block_run_id": 44, "block_uuid": "transform_fear_greed_index", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 44 (block_uuid: transform_fear_greed_index) completes.", "timestamp": 1713312044.300409, "uuid": "356e7e79c0df4e51ad1a8a0765dcbb80"}
2024-04-17T00:00:48 {"block_run_id": 48, "block_uuid": "export_binance", "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "EXCEPTION", "message": "BlockRun 48 (block_uuid: export_binance) failed.", "timestamp": 1713312048.42998, "uuid": "7ae6da28703e49e8b2bd13d5e50f3cd5", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1258, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1167, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1473, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1629, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 552, in with_config\n    return cls(**kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 74, in __init__\n    credentials = service_account.Credentials.from_service_account_file(\n  File \"/usr/local/lib/python3.10/site-packages/google/oauth2/service_account.py\", line 258, in from_service_account_file\n    info, signer = _service_account_info.from_filename(\n  File \"/usr/local/lib/python3.10/site-packages/google/auth/_service_account_info.py\", line 78, in from_filename\n    with io.open(filename, \"r\", encoding=\"utf-8\") as json_file:\nFileNotFoundError: [Errno 2] No such file or directory: '/home/src/secrets/secret.json'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 750, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 92, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1626, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 190, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1163, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["[Errno 2] No such file or directory: '/home/src/secrets/secret.json'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1258, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1473, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1629, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 552, in with_config
    return cls(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 74, in __init__
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/src/secrets/secret.json'
2024-04-17T00:00:51 {"cpu": 0.41845703125, "cpu_total": 8, "cpu_usage": 0.05230712890625, "memory": 2084.0, "memory_total": 4954.0, "memory_usage": 0.42067016552280984, "pipeline_run_id": 9, "pipeline_schedule_id": 1, "pipeline_uuid": "binance_fear_greed_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline binance_fear_greed_pipeline for run 9 in schedule 1 is alive.", "timestamp": 1713312051.029421, "uuid": "61fa2791709549c8983cd715f0e3ec99"}
